### ISSUE TITLE
prefer_int_literal false positive for max(xDouble, 1.0) ?

### ISSUE THREAD

**Issue by a14n** [dart-lang/linter#1231]
I'm not really sure but I think `1.0` shouldn't be flagged in `max(xDouble, 1.0)`.

IIUC `max(xDouble, 1)` has a result with a static type `num` which differs with `max(xDouble, 1.0)` that has a result with a static type `double`.

**Comment by bwilkerson** [comment]
Correct. Because `T max<T extends num>(T a, T b);` has a return type that is dependent (in part) on the type of the argument, we can't change the type of the argument without at least potentially changing the static type of the invocation.

**Comment by danrubel** [comment]
As it stands today, the lint does not replace double literal arguments in `Math.max` method calls because the method arguments are not of type `double`. I added a test to this effect in https://github.com/dart-lang/linter/pull/1233.

Please let me know if I missed a situation in which the lint is behaving incorrectly.
