### ISSUE TITLE
public_member_api_docs should ignore @visibleForTesting

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/linter#1245]
I'm not 100% sure whether this is the right solution, but initially I was surprised that this lint was triggered by a method annotated with `@visibleForTesting`. If a member is only public for a test then the intention is that it isn't part of the "true" public API.

On the other hand, it is still part of the actual public API and users may depend on it/docs will be generated for it.

**Comment by pq** [comment]
Interesting idea.  Thanks!

@bwilkerson and I have talked about a bunch of improvements to this rule and here's another case where it almost does what we want but not quite...

Brian: do you have any thoughts here?

**Comment by bwilkerson** [comment]
I completely understand the request, and empathize with it. If a member is `visibleForTesting` then it isn't intended to be used and shouldn't be required to be documented. That's also true for `visibleForOverriding`. And maybe for `experimental`. And who knows how many more in the future.

I'm wary in general of having too many exceptions on a lint, because it often indicates that the lint is not well defined. In this case I think the lint is well defined, but the notion of public is strained because of the lack of support for finer grained notions of visibility in the language.

If we had better language support for visibility, then I'd say no, that this isn't reasonable. But without better language support I don't know that I'd object to making the requested change.

But as @jonahwilliams points out, it _is_ public as far as the language is concerned, so maybe the better answer is to add a doc comment that explains that the member is not intended to be used outside of test code. :-)

**Comment by jonahwilliams** [comment]
Having slept on it a bit - I agree this is more of a case of wanting different visibility controls then are currently available. In that sense, it shouldn't really be the lint's responsibility to come up with a different system. Thanks @bwilkerson and @pq for the discussion (_Clearly we must add more visibility controls!_)

**Comment by bwilkerson** [comment]
@leafpetersen @lrhn In case it's interesting fodder.

**Comment by bartekpacia** [comment]
I think this shouldn't be closed :) would be great to have this
