### ISSUE TITLE
Avoid prefer_initializing_formals when parameter is named and the name is different from the field

### ISSUE THREAD

**Issue by dramos07** [dart-lang/linter#1587]
This example here is outside of the "when possible". If the parameter is named and the name is different from the field, then an initializing formal would force you to change the API of the class. In that case, you shouldn't use it.

```dart
class Foo {
  final bool isDisabled;
  Foo({bool disabled}) : this.isDisabled = disabled;
}
var foo = Foo(disabled: true);
```

The only 2 current possible fixes for prefer_initializing_formals:

### Solutions 1: Change the field to matched the named argument
```dart
class Foo {
  final bool disabled; // Goes against https://dart.dev/guides/language/effective-dart/design#prefer-a-non-imperative-verb-phrase-for-a-boolean-property-or-variable
  Foo({this.disabled});
}
var foo = Foo(disabled: true);
```

### Solutions 2: Change the named argument to match the field
```dart
class Foo {
  final bool isDisabled;
  Foo({this.isDisabled});
}
var foo = Foo(isDisabled: true); // Goes against https://dart.dev/guides/language/effective-dart/design#consider-omitting-the-verb-for-a-named-boolean-parameter
```

Either option contradicts the guidelines, but more importantly either would force you to change the API of the class.

**Comment by pq** [comment]
Thanks for the write-up!  I'm on the fence about whether the lint should not fire in this case.  What if a team opts in to this lint but does not subscribing entirely to the naming guidelines?  Another nuance is:

> either would force you to change the API of the class.

which is a great point.  Unfortunately we have a pretty under-developed notion of what constitutes an API proper and so it would be tricky to know when this would be an issue or not.

In practice, I guess I would think this might be a case where you'd want to suppress this warning specifically in this instance but not sure it would make sense to change the logic in general since knowing whether a change would be breaking and whether the naming conventions are being strictly followed requires situational awareness.

Having said all this, I'm still mulling it all over...  Thanks for the compelling example!

/cc @bwilkerson for thoughts.

**Comment by bwilkerson** [comment]
> ... what constitutes an API ...

I don't really want to debate what an API is right now, but I think it's fairly clear that both changes are breaking changes.

Given that, I'm strongly leaning toward agreeing that the rule should not create a lint in this case.

**Comment by pq** [comment]
> I don't really want to debate what an API is right now,

Ok, but **_I_** can't resist. 😄 

The distinction I'm getting at hinges on the opinion that it's only API breaking in an _interesting way_ if changes could affect someone.  If it's internal to a package or if this is code that is self-contained and never intended to be imported I don't think we should treat it the same way.  Assuming it's actually API in the sense that it is meant to be used, we should be mindful of API that's evolving vs. API that's been published.

In the end, I guess I'm advocating by potentially presenting too much advice, (erring I guess for possible false-positives) over being too conservative and missing the chance to add value.

On a meta level, should the fact that following advice could break an API stop us from providing it?  There are tons of places where we do that.  Should we reconsider those too?  (Or is this one somehow different?)

Thanks for the thoughtful conversation!

**Comment by bwilkerson** [comment]
As always, it's difficult to weigh the disadvantages of false positives against those of false negatives. It would be nice to have some data on which to base a conclusion, but I don't think we're likely to get that. I guess I tend to lean more heavily toward avoiding false positives, possibly because I'm more acutely aware of the consequences of them (lints don't tend to be unused because they have too many false negatives). While false negatives can lead to lost value, an unused lint leads to even more lost value.

But you're right, we don't refuse to lint other conditions that would cause an API to be broken, so perhaps it's not as strong an argument as it initially seemed.

I guess another question to ask is whether the specific case before us is a valid exception to the guideline, and should be treated as such by not creating a lint in those cases.
