### ISSUE TITLE
Analysis lint for trailing whitespace

### ISSUE THREAD

**Issue by dnfield** [dart-lang/linter#1717]
Flutter has a custom script to check for whitespace at the end of files. It'd be nice to have this as an analyzer lint for dart files so the IDE could warn you ahead of time, at least for Dart, and assuming you're either not using dartfmt or haven't formatted yet.

**Comment by srawlins** [comment]
The linter will not replicate whitespace rules already implemented in dartfmt.

An example of a formatting rule that _is_ implemented in the linter, because the formatter does not split strings or comments, includes [lines_longer_than_80_chars](http://dart-lang.github.io/linter/lints/lines_longer_than_80_chars.html).

The formatter does already collapse all whitespace at the end of a file, and ensures the file ends in a newline. I think these are exactly the two requests you are making, @dnfield. Is there a reason end-of-file whitespace is unique, or separate from other whitespace lint rule possibilities?

**Comment by dnfield** [comment]
We don't use dartfmt in Flutter - for various reasons.  We do expect users to not have whitespace at the end of lines and to have a new line at EOL.  It seems like it would be nice if the analyzer could help with that, although I understand the reluctance given that the formatter can already do this.  We can just continue with our home grown script, but it would be one way to remove a surprise from a relatively small group of users.

**Comment by srawlins** [comment]
I see, while `class C{   }` has glaring whitespace issues, a file missing a trailing newline, or having two newlines, etc. is easily missed until the presubmit script hollars at you.

**Comment by pq** [comment]
Hey @dnfield.  I was looking into this a bit ago and got distracted; sorry!  Confirming this would still be valuable?

**Comment by dnfield** [comment]
I think so  - although I say that assuming this wouldn't be an especially difficult one to implement and that it shouldn't be very highly prioritized.  But it could give helpful feedback to Flutter contributors who are encouraged not to use dartfmt.

**Comment by pq** [comment]
@dnfield: I'm hoping that @asashour's new `eol_at_end_of_file` should be sufficient for you all?

(It's not landed in the SDK yet but will be on our next roll.)

**Comment by pq** [comment]
This is implemented with `eol_at_end_of_file`. 👍
