### ISSUE TITLE
Are there linting for duplicate code?

### ISSUE THREAD

**Issue by zaralockheart** [dart-lang/linter#1762]
As code in a project grow, developers may write duplicate codes without realising it. Are there any ways to detect duplicate code?

**Comment by bwilkerson** [comment]
Not yet. It's something that I have some interest in myself, and I think it would make a great addition to our tooling.

I don't believe, however, that we'd implement it as a lint because I think it requires doing more analysis that we can afford to do in a lint (that is, the lint would be too slow). I do have some ideas of how to potentially reduce the time, so I might be wrong about that, though.

It's also not clear to me that users would want to have this kind of analysis running as they type.

**Comment by zaralockheart** [comment]
I got warning of duplicate code when I code with typescript. So I think it would be great if Dart has the feature too :)

**Comment by pq** [comment]
@bwilkerson: should we move this over to the SDK repo to track as an analyzer feature request?

**Comment by bwilkerson** [comment]
I think that would be appropriate. Then it doesn't presuppose that we'd use a lint rule to provide the functionality.

**Comment by pq** [comment]
cc @mit-mit for (another) `move` config question...

**Comment by zaralockheart** [comment]
I open another issue [here](https://github.com/dart-lang/sdk/issues/38930)
