### ISSUE TITLE
rationalize string lints

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2002]
Following up on the various conversations about string lints, let's take a step back and look at what we want to enforce and see if we can agree on a path towards a (minimal) set of lints to capture best practices.

Needless to say, thank you so much @a14n for driving this effort.  Your contributions here (and elsewhere with the linter) are greatly appreciated and always welcome! 🙏 

/cc @bwilkerson

**Comment by pq** [comment]
Friendly bump.  I plan to do a linter release in the next few days and would love to have a plan here before I do.  If we need a bit more time, we could de-register the lints in question so that any changes aren't API-breaking.

@a14n, @bwilkerson: thoughts?

**Comment by a14n** [comment]
IIUC this issue is about having 2 separated lints [change_quotes](https://github.com/dart-lang/linter/pull/2000) and [unnecessary_escapes_in_string](https://github.com/dart-lang/linter/pull/1996) (and perhaps [unnecessary_raw_strings](https://github.com/dart-lang/linter/pull/2001)) or a single lint (say `simplificable_strings`).

My preference is to keep several lints for the various reasons mentioned in #2000 but if you really want a single lint I can live with that (and I'll wait for an issue asking to split it :stuck_out_tongue: ).

What would be the preference of a lint user like @davidmorgan ?

**Comment by davidmorgan** [comment]
From the point of view of google3/pedantic: I think we don't need `change_quotes` since we enforce `prefer_single_quotes`? `unnecessary_escapes_in_string` looks like one we'll want to add.

More generally: if we had five separate recommended lints related to string use we could roll them up into one that is equivalent to enforcing the five ... but that wouldn't make a huge difference, since users still have to discover that that lint is recommended and enable it. And, there's no guarantee the recommendation will be the same forever.

I think this problem is best solved by packages like package:pedantic giving recommendations. We could build on that by making recommended sets discoverable in tooling. That path would tend to prefer smaller lints, since we're not expecting users to discover and enable them one by one, and it gives more flexibility for us to choose what we recommend and for individuals to tweak if they like.

Not a strong opinion, though :)

**Comment by a14n** [comment]
> From the point of view of google3/pedantic: I think we don't need `change_quotes` since we enforce `prefer_single_quotes`?

`prefer_single_quotes` accepts double quoted strings as long as they contain a single quote like `"it's ok"`. See: https://github.com/dart-lang/linter/blob/e727b9b8d78be6a80e28629e8b12a391f9788261/lib/src/rules/prefer_single_quotes.dart#L40

**Comment by davidmorgan** [comment]
Right, sorry; `change_quotes` and `prefer_single_quotes` are not too closely related. `prefer_single_quotes` lets you choose between

```
'a quote \'in\' a quote'
```

and

```
"a quote 'in' a quote"
```

--at first glance I don't see a strong downside to letting people make this choice, i.e. I think we would not enforce `change_quotes`, but probably would enforce `unncessary_escapes_in_string`. It's a (google internal) community process, though, so I can't say for sure :)

That points to wanting them to be separate lints.

I guess another question is whether it's useful to go through the `pedantic` approval process _before_ adding lints. Note that that process involves checking for pre-existing violations in all the google internal Dart code, so we can see what would have to change, so we do need to have an implementation ready. I don't mind lints being added that we won't enforce, it's more a question to you as to whether you want to have enforcement in `pedantic` as a goal :)

**Comment by pq** [comment]
Great discussion.  Thanks!

> I don't mind lints being added that we won't enforce, it's more a question to you as to whether you want to have enforcement in pedantic as a goal :)

I wouldn't make it a goal but internal usefulness **_is_** a great motivator.

Given the unlikelihood of internal adoption of `change_quotes` and `unncessary_escapes_in_string`,  I'm now leaning towards keeping them separate.  I still think discovery is a problem there's only so much we can do.   

A few cleanup thoughts along those lines (and beyond):

* update `change_quotes` to `avoid_escaping_inner_quotes` (which feels to me a bit more consistent w/ our names generally)
* add links between string-related lints in their docs
* consider changing `unnecessary_escapes_in_string` to `unnecessary_string_escapes` (shorter) or `unnecessary_escapes_in_strings` (I think there's more precedent of plurals)

Thanks again for the thoughtful discussion!

**Comment by pq** [comment]
I think we can close this conversation for now.

Thanks again all!
