### ISSUE TITLE
Support #noqa -like comments

### ISSUE THREAD

**Issue by dvorapa** [dart-lang/linter#2043]
**Describe the issue**
As a dev I would like Linter to skip some single lines I don't want to fix and don't throw a Linter warning there.

I don't want to skip the whole rule because of one two lines and also don't want to see these warnings every time I lint my scripts.

In Python this works with `#noqa` and `#noqa: issue-id` (`#noqa: issue-id, issue2-id`) comments after the line. In Dart it would probably be `//noqa`, etc.

**Expected behavior**
Linter would either skip issues in lines with this comment, or ignore issues with specified id

**Comment by pq** [comment]
@dvorapa: is the `ignore` and `ignore_for_file` support sufficient?

See: https://dart.dev/guides/language/analysis-options#suppressing-rules-for-a-file

**Comment by dvorapa** [comment]
This should be noted in https://dart-lang.github.io/linter/

ignore_for_file does not work for undefined_lint_warning

**Comment by pq** [comment]
Hi @dvorapa, do you mean in the readme?  Looking at https://github.com/dart-lang/linter, it's there actually:

![image](https://user-images.githubusercontent.com/67586/77363807-9d0cfd80-6d10-11ea-940b-b0f76012a8b2.png)

> ignore_for_file does not work for undefined_lint_warning

Out of curiosity, why would you want to ignore an undefined lint?  That seems like an error...

**Comment by dvorapa** [comment]
Ah, so there's a part in Dart language guide, part in Linter website and part in Linter readme. I expected all information to be in one place (and thought Linter website is that place).

Undefined lint warnings are completely normal if you update analysis_options.yaml from Linter website frequently, but new Dart release is still not delivered to your platform/distro yet.

**Comment by pq** [comment]
Yeah.  At this point the information is a bit duplicated.  For sure there are opportunities to improve (fyi @kwalrath).

> Undefined lint warnings are completely normal if you update analysis_options.yaml from Linter website frequently, but new Dart release is still not delivered to your platform/distro yet.

OK.  Thanks for the clarification.  This is a little tricky since there's currently no way to know when the `ignore` is no longer needed (among other things).  Anyway, more generally, ignores are currently unsupported in `analysis_options` so we'd have to start with that.  Feel free to open a feature request on the [Dart SDK](https://github.com/dart-lang/sdk/issues/new) if you want it to get considered.

Closing this one for now.  Thanks for the feedback!
