### ISSUE TITLE
lint to ensure exhaustive enum-like class switches

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2083]
**Exhaustive enum-like class switch**

For classes that define private constructors, and a number of static const instances, switching on an instance of that class should be exhaustive. This should cover e.g. proto enums and other cases.

Open question: is inferring "enum-like" characteristics sufficient, or do we need a formal annotation?

**Comment by bwilkerson** [comment]
> ... is inferring "enum-like" characteristics sufficient ...

I suspect that it's sufficient, but I don't know how to answer that question definitively unless we constrain it to "sufficient for the cases we know about today". With that constraint, we can make a list of cases we care about and decide whether there is enough signal to be able to distinguish between code that we intend to lint and code that we don't intend to lint.

Thinking about it a little more, I suspect that the criteria is that a class is enum-like if
- it is a concrete class,
- it has no public constructors (so that we can know all the places instances are created),
- all of the private constructors are generative constructors (not factories),
- it has two or more `static const` fields whose type is the enclosing class and whose initializers are simple invocations of those private constructors,
- the private constructors are not invoked anywhere other than in the static final fields, and
- there are no subclasses of the class in the defining library.

**Comment by pq** [comment]
On some investigation, the following details are not available in the analyzer's element model: 

* it has two or more static const fields whose type is the enclosing class and ~whose initializers are simple invocations of those private constructors,~
* the private constructors are ~not invoked anywhere other than in the static final fields~

so for a first cut I don't think we can enforce how enum-like fields are initialized or if there are any other instances created outside the initialized fields.  I don't expect, in practice, this to lead to (m)any false positives but it's worth being aware of.  If we hit snags, I think an annotation-based approach is probably our most solid bet.

/fyi @jefflim-google
