### ISSUE TITLE
String literals inside regular expressions should have a hint to be 'raw'.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/linter#2156]
It is a common mistake to write Regular Expressions with the wrong string-literal.
For example `new RegExp('\d+')` instead of `new RegExp(r'\d+')`.

It would be great if the analyzer gave a hint (especially if there was an escape in the string).

**Comment by srawlins** [comment]
Because of the risk of false positives, and conflict with other lint rules, I've decided to move this to be a linter request.

**Comment by pq** [comment]
Will these issues get caught by the existing rule [valid_regexps](https://dart-lang.github.io/linter/lints/valid_regexps.html)?

**Comment by bwilkerson** [comment]
Not in all cases. I think the issue that Florian was pointing out was that it's hard to tell whether the string should have been raw in order to prevent escape characters to be translated or string interpolation to be performed. Using the example above, `'\d+'` is equivalent to `'d+'` (the backslash is effectively erased), but the intent was for `\d` to name a character class.

The difficulty with the request is that there's no way to statically determine whether the raw or non-raw form is correct (unless the current form doesn't parse, in which case the lint would trigger).

I don't think this is practical, so I think we should close it.
