### ISSUE TITLE
Consider linting on casts from nullable to non-nullable types.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/linter#2235]
When casting to a type in null safe Dart, it's easy to forget to account for null.  For example, casting directly from `dynamic` to `int` doesn't account for `null`: the user should either have handle the null case before casting, or else should cast to `int?` and then handle null from there.  Some users may prefer to enforce this via a lint. See https://github.com/dart-lang/language/issues/1170 for further discussion.

cc @Hixie

**Comment by Hixie** [comment]
My bigger concern is actually casting from `Foo?` to `Bar` where Bar is a subclass of Foo, especially in cases where the source type (Foo?) isn't visible in the code, e.g. because you're casting the return value of a method or getter. Porting the framework I see lots of cases where we accidentally do that without checking for null, and because there's no `!` present, we're basically losing all the "null safety" aspects of Dart but it's even worse than before NNBD because now it _looks_ safe.

**Comment by Silentdoer** [comment]
please support really null safety types, currently int? or double? or ... is fake null safety type like java's generic type.

**Comment by a14n** [comment]
In #2244 I implemented a lint that explicitly allows casting from dynamic (based on what I saw in flutter codebase) and also allows casting from `T?` to `T`. Should those 2 cases be also be catched? WDYT?

**Comment by Silentdoer** [comment]
Maybe let T? equals Nullable<T> is a good choice?
int? equals Nullable<int>, int? a = 8;then int s = a! will auto unboxing call a.getValue();

**Comment by Hixie** [comment]
I have no problem casting from dynamic. I consider dynamic to be magic, and honestly I'd probably be ok with silently casting from dynamic in general, without even an `as` or a `!`.

I don't feel strongly about `T?` to `T` but I think it would be reasonable to disallow that if we're going down the path of saying you should always have a `!` if you are assuming non-nullability. It makes the code more consistent and predicatable.

**Comment by a14n** [comment]
Thanks, I will update the lint to catch `o as String` if `o` is of `String?` type.
