### ISSUE TITLE
consider enforcing sort order in the build

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2368]
See churn in https://github.com/dart-lang/linter/pull/2362.  Also, discussion in #2367.

**Comment by pq** [comment]
Now that we're in the SDK, we can do this easily. 🎉

**Comment by pq** [comment]
Implemented w/ https://github.com/dart-lang/sdk/commit/349e6266ff67f645dcf24155c2b3cf3334f0fdc0.

**Comment by parlough** [comment]
One less thing to consider 🥳

**Comment by pq** [comment]
💯

**Comment by pq** [comment]
We've wanted this for a while. Nice reward for the long haul of migrating the linter into the SDK!

**Comment by parlough** [comment]
I wonder why your commits aren't closing the linked issues automatically? Is it because you're not actually committing, but the Commit Queue is? I've had the same problem with closing site-www issues from the SDK before.

**Comment by pq** [comment]
I'm not sure to be honest.

@whesse @athomas?

**Comment by athomas** [comment]
I believe it's because copybara (the tool that pushes the code from googlesource.com didn't have push access to the linter repo). I made an attempt at fixing that. Let me know if it works!

Background: to close issues in another repo the user pushing the commit has to have access to the other repo. I couldn't find documentation on what access exactly, though. GitHub scans the pushed commits for keywords and then applies its own rules to decide what to do.

**Comment by pq** [comment]
Thanks for looking!

Not sure it worked unfortunately. I had to make a manual edit here:

**Comment by athomas** [comment]
> Not sure it worked unfortunately. I had to make a manual edit here:

Unfortunately, I don't know... 🤷

This is basically what we're doing but I'm not sure what permission we need to grant the bot:
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-an-issues-only-repository

 It's an "app" so I can't grant it write access to linter specifically, and it already has write access to every repo.

**Comment by pq** [comment]
Ah well. Thanks for looking!

On the bright side, the plan is to move the linter issues over to the SDK sooner than later so the issue won't be long lived.

Again, thanks!
