### ISSUE TITLE
Standardize on whether GOOD or BAD comes first in docs

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/linter#2488]
Some lint docs list the GOOD example first (e.g. https://dart-lang.github.io/linter/lints/no_adjacent_strings_in_list.html) others list the BAD example first (e.g. https://dart-lang.github.io/linter/lints/hash_and_equals.html).

Maybe the order could be standardized?

**Comment by bwilkerson** [comment]
I'd actually like to see the docs re-written in the style of our other diagnostic messages (https://dart.dev/tools/diagnostic-messages). Rather than good and bad, have examples of bad code and how it should look when it's cleaned up.

But it will probably be awhile until I can get that done, so standardizing would be a good short-term goal.

**Comment by srawlins** [comment]
CC @asashour

**Comment by asashour** [comment]
This is may be due to some rules description start with `DO`/`PREFER`, while other are `DON'T`/`AVOID`.

There are currently 149 rules which `BAD` comes first, while 57 `GOOD` comes first.

Based on that, and on the previous comment, I think `BAD` should come first.
