### ISSUE TITLE
consider nonfunction type alias support in `avoid_private_typedef_functions`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2535]
As per the discussion in https://github.com/dart-lang/linter/pull/2534, it's not obvious whether `avoid_private_typedef_functions` should be expanded to support nonfunction type aliases.

Specifically cases like:

```dart
typedef _T = Object; // LINT?
mixin M { }
class _C = Object with M; // LINT?
``` 

/cc @davidmorgan @hixie @goderbauer

**Comment by Hixie** [comment]
I don't really see the value in avoid_private_typedef_functions at all, so... :-)
(I see the value in https://github.com/dart-lang/linter/issues/2519, and it would apply to non-function type aliases, yes.)

**Comment by eernstg** [comment]
The [documentation](https://dart-lang.github.io/linter/lints/avoid_private_typedef_functions.html) seems to imply that the motivation for `avoid_private_typedef_functions` was to encourage the use of inline function types:

> AVOID private typedef functions used only once. Prefer inline function syntax. 

The reference to `private` is probably there because it is possible to determine modularly that a given type alias is used only once when it's private, but for a non-private type alias there could always be additional usages that we don't know about.

So the single-use type alias would be written by a person who hasn't yet heard about inline function types. Aren't such persons rare today?

Also, it doesn't really apply to the non-function type aliases (because they denote types that we've always been able to write inline).

All in all, I don't think there's a lot of value in having this lint today.

**Comment by pq** [comment]
Fantastic.  Thanks a million for the thoughtful feedback.  I'll consider this one "considered" and close it out.

Much appreciated!
