### ISSUE TITLE
unused import

### ISSUE THREAD

**Issue by asashour** [dart-lang/linter#2758]
**Description**

Hint about an unused import, which is redundant.

**Comment by parlough** [comment]
Hey @asashour, I agree this would be nice. I believe work on this is currently being done to implement this as a hint directly within the analyzer. You can see the hint definition here: https://github.com/dart-lang/sdk/blob/d08a059f6bdf404d87622a3ff47182c00fd50532/pkg/analyzer/lib/src/dart/error/hint_codes.dart#L2974

**Comment by pq** [comment]
+1 to what @parlough wrote.  This feels best implemented as a hint.

maybe @bwilkerson or @scheglov can chime in on status?  (Or if there's an issue we can link to, that'd be great.)

**Comment by pq** [comment]
I think this is probably best tracked in: https://github.com/dart-lang/sdk/issues/44569.

@asashour : please feel free to chime in there if it looks like anything was missed.

Thanks!

**Comment by bwilkerson** [comment]
@asashour The unused import hint has been implemented in the analyzer for several years now. The issue that Sam opened is related to some additional cases that were originally missed. If there is a case where the analyzer failed to catch an unused import, please add it to dart-lang/sdk#44569 so that we can investigate adding support for it.

I'm closing this issue in favor of the one in the SDK repo.
