### ISSUE TITLE
directives_ordering rule should order also show/hide list

### ISSUE THREAD

**Issue by nguyenxndaidev** [dart-lang/linter#2785]
`export 'a.dart' show B, A;` should be formatted to `export 'a.dart' show A, B;`
Same should be applied to `hide`.

**Comment by srawlins** [comment]
And I'll move it over to the linter repo. 😄 

However, this sounds like a separate rule. For one thing, someone might want to order their directives but not the combinators, or vice versa.  For another thing, it would be a large, breaking change to enforce this second functionality via the current linter rule. I'll let @pq comment.

**Comment by bwilkerson** [comment]
I think that making it a separate lint is probably required. Whether the lint has enough value is for the community to decide, but we probably want to get wider feedback before implementing it.

**Comment by pq** [comment]
Curious if @davidmorgan or @michalt have thoughts about export ordering conventions internally?

**Comment by michalt** [comment]
@pq I'm not aware of any explicit conventions. I've done some spot checks and it seems that:
- There are not that many exports with explicit `show ...`.
- Many of them are already alphabetically sorted.

I do agree with @bwilkerson that we'd want a new lint, so that we can disable it at first, discuss internally whether to enforce it, and only then start doing cleanups.
