### ISSUE TITLE
[Suggestion]: Flag statements of the form: x == y; as "statement yields unused boolean"

### ISSUE THREAD

**Issue by jonmountjoy** [dart-lang/linter#2873]
I just found a bug after a hard search, and I had written this:

    itemState.learningAspect == LearningAspect.learnContext;

instead of

    itemState.learningAspect = LearningAspect.learnContext;

Is it possible for a lint rule to have caught this?  (A better font would have helped me too)

ie. this should be flagged:
  
    var x = 1;
    x == 2;  // <===. would love this to be a lint error: "statement yields an unused boolean"

It's probably a warning, rather than an error - though I honestly can't imagine anyone really wanting to write a line like that, no matter how complex, but appreciate there may be a reason I can't think of.

There are probably some complexities around function calls.  For example, if `f()` returns a boolean:

    f();

In this case, I'm less certain that I want it flagged.

Thank you.

**Comment by bwilkerson** [comment]
I would have expected that this case was already handled by `unnecessary_statements`. Does that lint fail to flag this case?

**Comment by jonmountjoy** [comment]
Ahhh.  That does the job - thank you @bwilkerson .
Also worth noting: the pedantic analysis options does not have `unnecessary_statements` switched on, nor does the new https://github.com/dart-lang/lints#migrating-from-packagepedantic 

Thanks again!

**Comment by bwilkerson** [comment]
I believe the reason this lint isn't on in those rule sets is because of the false positives. For example, the lint assumes that implementations of the equality operator won't have side effects and hence it's safe to remove its use. But that isn't always the case, so the lint might suggest removing code that's really needed because of side-effects. It's uncommon, but the rule set authors tend (correctly, imo) to be very conservative when adding lints.
