### ISSUE TITLE
🟢  ☂️   rename "master" branch to "main"

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2923]
Following Dart, Flutter, Chrome et al., and inspired by conversations such as [this one](https://lore.kernel.org/git/pull.656.v4.git.1593009996.gitgitgadget@gmail.com/), I'd like to migrate the linter to "main".  Though we don't use `gclient` for development, the SDK (which has the linter in `DEPS` does) and I understand from @athomas that _may_ complicate things and we should wait until the SDK is fully moved over.  Holding here until we get the green light.

All: please feel free to chime in on this tracking issue if you have thoughts or concerns.

(For reference, here's the  [Changing the default branch doc](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch ) and a [GitHub renaming guide](https://github.com/github/renaming).)

---

Punch list of things to update when we go ahead:

- [x] `CONTRIBUTING` (#3518)  
- [x] `.github/workflows` (#3518)  
- [x] `README` and scoring scripts (for SDK and Flutter links) (#3518)  
- [x] `doc/**` (#3518)
- [x] (internal) update copybara scripts (cl/460768093)

**Comment by athomas** [comment]
@pq I think we should try to do this. I can't see any reason why it won't work:

- DEPS doesn't contain information about the branch the hash is on.
- We've previously seen that `gclient sync` was able to pull changes even from branches used just for PRs (not that that's a good thing, but it's further evidence that the branch name doesn't matter).
- We already pull in `pkg:lints` into the SDK which uses `main` as a default branch.

When you do decide to move forward, please keep an eye on the console for a few hours and be prepared to re-create a master branch if purpleness starts to show up (it should be sufficient to create another branch called `master` that has all the commits from `main` rather than renaming `main` to `master`). There's a risk some caches on the bots might be affected by this change (though I think that risk is very low).

**Comment by athomas** [comment]
@pq See also email thread about potential internal infra impact.

**Comment by pq** [comment]
@iinozemtsev : do you know if any of your scripts (e.g., `find_violations`?) will need updating?

**Comment by pq** [comment]
The scorecard analysis workflow is borked w/ this migration:

https://github.com/dart-lang/linter/actions/runs/2665184251

(But maybe that's just until this change lands and updates the workflow?)

/fyi @sealesj

**Comment by sealesj** [comment]
@pq It will need a manual change but is just a one-liner update on the scorecards repo
https://github.com/dart-lang/linter/pull/3519

**Comment by pq** [comment]
Thanks!  I think that change is actually subsumed by #3518 (which has other workflow updates too).

**Comment by sealesj** [comment]
@pq Awesome! I'll close out the scorecards PR

**Comment by pq** [comment]
Sorry for the noise.  In retrospect, it's clear that I just needed to wait for #3518 to land.

Thanks so much for your help!

**Comment by pq** [comment]
With `copy.bara.sky` updated I think this is complete.

@athomas, @iinozemtsev: please re-open if there are any loose ends internal or elsewhere?

Thanks!

**Comment by iinozemtsev** [comment]
I'll take a look tomorrow, but copybara update shouldn't be a blocker, in
worst case it will just copy some commits a bit later

Phil Quitslund ***@***.***> schrieb am Mi., 13. Juli 2022,
20:45:
