### ISSUE TITLE
`prefer_mixin` lacks nuance

### ISSUE THREAD

**Issue by Hixie** [dart-lang/linter#3018]
The `prefer_mixin` lint points out uses of `with` that mix in classes rather than mixins.

Unfortunately, sometimes a class is _intended_ to be used as both a mixin and a class, and there's currently no way to indicate that a particular class is therefore ok for use with `with`.

Examples in Flutter's framework include `WidgetsBindingObserver` and `ChangeNotifier`.

**Comment by pq** [comment]
We make some exceptions for a few SDK classes

* `IterableMixin`
* `ListMixin`
* `MapMixin`
* `SetMixin`
* `StringConversionSinkMixin` (dart:convert)

as a holdover until changes on the SDK-side let us handle this in a more principled way.  It's not an awesome solution but we could consider adding `WidgetsBindingObserver` and `ChangeNotifier` to the allow-list?

@lrhn: I wonder if there are any updates relevant to this from the SDK or core lib perspective?

**Comment by lrhn** [comment]
I stand by https://github.com/dart-lang/language/issues/33#issuecomment-886476373

The problem is migration. If someone currently `extends` a class we want to convert to a mixin, then it's breaking to change it.
We could add an annotation meaning "this is intended as a mixin", and make it a warning to extend such a class (you'd have to write `with` instead). Then eventually we could make the change.
I suggested that in https://github.com/dart-lang/language/issues/1529.

I'm more inclined towards a language version based migration, like https://github.com/dart-lang/language/issues/1643.

**Comment by pq** [comment]
See also, https://github.com/dart-lang/language/issues/1942.

**Comment by robert-j-webb** [comment]
Hey ran into this when using `ChangeNotifier` and `WidgetsBindingObserver` 

Is there some kind of canonical solution to this? We should probably update the linter message to help users resolve this.

I had a class like this

```dart
class SomeModel extends ChangeNotifier with WidgetsBindingObserver {
```

Which gave me the error: Prefer using mixins. See [https://dart-lang.github.io/linter/lints/prefer_mixin.html](prefer_mixin)


and I converted it to this:

```dart
class SomeModel with WidgetsBindingObserver, ChangeNotifier {
```

but that still triggered the lint? Sorry I'm not a dart wizard so I don't really know what the correct solution should be here. I'm happy to just ignore the lint but it doesn't feel right.

**Comment by pq** [comment]
The issue here is that `WidgetsBindingObserver` is a **class** that you're using as a mixin.  It looks like it is designed to be potentially used that way so this is not really a problem of yours but reflects our lack of support for classes that are kind of exceptionally mixin-able.

Reading the docs for [`WidgetsBindingObserver`](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html) am I right that you're only getting stubbed methods?  If that's the case maybe you could just _implement_ it instead (and provide your own implementations)?

```
class SomeModel extends ChangeNotifier implements WidgetsBindingObserver
```

@goderbauer: any advice here?

**Comment by goderbauer** [comment]
I don't have great advice, unfortunately. That lint doesn't work well with some of the concepts in the flutter framework that pre-dates mixins, see also https://github.com/dart-lang/lints/issues/26.

However, it is totally fine to implement the WidgetsBindingObserver as @pq suggested. You'd probably just have to copy a lot of the empty stubs from the base classes to fully implement the interface. Or you can just ignore the lint with `// ignore: ...`.

To really fix this, we'd need some changes to the dart languages, as discussed in the issues linked from ttps://github.com/dart-lang/lints/issues/26.

**Comment by goderbauer** [comment]
With the `mixin` modifier, this is likely no longer an issue and can be closed. We are also now able to enable this lint in flutter: https://github.com/flutter/flutter/pull/123159.

**Comment by pq** [comment]
Good deal. Thanks @goderbauer!
