### ISSUE TITLE
`avoid_catches_without_on_clauses` false positives

### ISSUE THREAD

**Issue by Hixie** [dart-lang/linter#3023]
One valid use for catching all exceptions and errors is to forward them to some error reporting logic, for example, the way that Flutter frequently catches all exceptions and forwards them to `FlutterError.reportError`.

It would be nice if a function like `FlutterError.reportError` could be annotated as a valid reason to catch exceptions, such that if the `catch` block contains a call to such a function, it isn't flagged with `avoid_catches_without_on_clauses`.

**Comment by Hixie** [comment]
Forwarding to `Completer.completeError` would be another example of a valid reason to catch all exceptions.

**Comment by bwilkerson** [comment]
I wonder whether there's a better way to formulate the lint (something other than "don't do this broad thing except in these 5 cases"). Maybe one or more specific use cases that should unconditionally be avoided.

**Comment by srawlins** [comment]
> I wonder whether there's a better way to formulate the lint (something other than "don't do this broad thing except in these 5 cases"). Maybe one or more specific use cases that should unconditionally be avoided.

> (2) cases where someone wants to catch a specific exception but casts a much wider net than necessary (e.g. they just need to catch FormatException but they actually catch everything).

This sounds like it would be hard to detect accurately. I think it may be hard to invert the rule's logic to target this case.

On the other hand, might not be to hard to just make some allowances for the above exceptions like:

* If the caught error is passed to `FlutterError.reportError`, `Completer.completeError`, or `Future.error`, allow it.
* If the caught error is passed as an argument to any function, whose return value is immediately thrown (i.e. the invocation is the `expression` in a ThrowStatement), allow it.
* If the body of the catch has any `rethrow`, allow it.

**Comment by bwilkerson** [comment]
> ... just make some allowances for the above exceptions like ...

That sounds reasonable to me.

We might also consider adding

- If the caught error is passed as an argument to any function whose return type is `Never`.

**Comment by srawlins** [comment]
Ooh good thought. I can add that one.

**Comment by Hixie** [comment]
My only note would be that instead of hard-coding `FlutterError.reportError`, `Completer.completeError`, and `Future.error`, there be an annotation that those things have that gives them the magic ability. That way someone who develops a new framework can get the same integration with the lint.

**Comment by srawlins** [comment]
It would take years to get that annotation into `dart:core` or a `pragma` annotating `Completer.completeError` and `Future.error` so I'll just hardcode them.

**Comment by srawlins** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/500a8c0a72851ac95f60685e66df035246ca97c6

**Comment by goderbauer** [comment]
This bug was also linked as a blocker for enabling the `avoid_catching_errors` lint in Flutter and when enabling it I am essentially running into the same classes of problems:

* It flags when `Error`s are caught that are later `rethrow`n  after resetting some state.
* It flags when `Error`s are caught to then throw a new `Error` with a more specific error message.
* It flags when `Error`s are caught and directly passed to an error processing function (e.g. `FlutterError.reportError`)

I am wondering if the same linience that was extended to `avoid_catches_without_on_clauses` in https://github.com/dart-lang/sdk/commit/500a8c0a72851ac95f60685e66df035246ca97c6 should also be applied to `avoid_catching_errors`? 

FWIW, most of the uncovered reports of `avoid_catching_errors` are inside asserts to improve the debugging experience when those Errors happen during development. I wonder if catches in asserts should generally be exempt from the `avoid_catching_errors` lint or whether just those specific categories mentioned above should be exempt from the lint.
