### ISSUE TITLE
unnecessary_parenthesis: missing case of item in a list

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/linter#3046]
```dart
final items = [
  1,
  2,
  3,
  (DateTime.now()), // LINT
];
```

Expect a lint on that last line – but don't get it!

**Comment by FMorschel** [comment]
I saw some commits here. Will https://github.com/dart-lang/linter/issues/4980 and https://github.com/dart-lang/linter/issues/4996 be addressed along side this one?

**Comment by srawlins** [comment]
Thanks for asking! I'm going to cruise around all of the open unnecessary_parenthesis issues and see if I fixed them, because that last commit was big. I probably want to add test cases for the other issues, if they were recently fixed.

https://github.com/dart-lang/sdk/commit/db35cbf6d96524ddd64d989cbe3ed11bb274706e fixes this issue, but I want to make sure it sticks, so I'll leave this open for another day or two.

**Comment by srawlins** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/db35cbf6d96524ddd64d989cbe3ed11bb274706e
