### ISSUE TITLE
Have pub run test -N print AST on failure

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/linter#305]
Follow up from #304 
Before, when tests failed it was handy to see the analysis result and ast printed on screen to understand the error cause. Could you please restore it? cc @pq 
Thanks!

**Comment by pq** [comment]
Ah yes, that was totally an oversight.

I'm not sure we want to get it going for `pub run test` since that will generate LOTS of extra output when we don't necessarily want it (in CI systems for example) but here's a change that restores it for the more debug-friendly `rule_debug.dart`.  

https://codereview.chromium.org/2315613003/

Running that looks like the old `solo_test`:

    dart test/util/rule_debug.dart valid_regexps

Let me know what you think!

**Comment by pq** [comment]
OK.  On second thought, I'm in favor of turning on the flag so that `pub run test` just works.  There's only noise when tests fail (which really shouldn't happen 😉 ).

CL updated: https://codereview.chromium.org/2315613003/

@alexeieleusis : PTAL!

**Comment by alexeieleusis** [comment]
Awesome, thank you!
