### ISSUE TITLE
consider a lint to encourage use of super-initializers where possible

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3174]

**Comment by bwilkerson** [comment]
Just brainstorming, but I believe that the lint will need to verify that
- the constructor is a generative constructor,
- the parameter is passed to a super constructor,
- either the parameter isn't referenced in the body of the constructor or there is a getter and/or setter with the same name (and we might want to drop the latter condition to avoid false positives),
- the type of the parameter is a subtype of the type of the corresponding parameter in the super constructor, and
- if the super constructor invocation has any positional arguments then all of the positional arguments could be converted to be super initializer parameters.

There are probably more restrictions that I'm not thinking of that will be needed in order to prevent false positives.
