### ISSUE TITLE
`prefer_contains` false positive when `indexOf` has a second arg

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/linter#3546]
I hit this running `dart fix` on `swarm` and trying to compile.  

Running:
> cd samples-dev/swarm
> dart fix .

generated this change:

https://dart-review.googlesource.com/c/sdk/+/252520/1/samples-dev/swarm/SwarmViews.dart#b590

which I had to manually fix here:

https://dart-review.googlesource.com/c/sdk/+/252520/1..2/samples-dev/swarm/SwarmViews.dart

> dart --version
Dart SDK version: 2.19.0-edge.d795274248204d94c9b3e09958b99da7f7428b13 (be) (Mon Jul 18 21:59:43 2022 +0000) on "macos_arm64"

**Comment by vsmenon** [comment]
Hmm, weird.  Transfer worked for me.

If the `indexOf` second arg is `0`, that could be handled the same as no second arg, right?

**Comment by bwilkerson** [comment]
I couldn't transfer it because `linter` wasn't in the drop-down list. I don't know how that list is populated, but it's possible I'm missing some level of access to something.

Yes, an index of zero would have the same semantics as not having a second argument. If the lint is currently handling that case specially (or if it does when we stop reporting the lint when there's a second argument), then the fix will need to be updated to delete the second argument.

**Comment by pq** [comment]
Great catch.  Thanks @vsmenon!

> If the lint is currently handling that case specially

It's not, but will as of #3548 👍.
