### ISSUE TITLE
proposal: `disallow_not_is_operator`

### ISSUE THREAD

**Issue by DaDummy** [dart-lang/linter#3611]
## Description

Disallow the unintuitive `is!` operator, promoting the more explicity `!(variable is Type)` to avoid confusion about a suffixed `!` being about falsyness instead of nullability.

## Details

During code review it may lead to false assumptions and confusion when a suffixed `!` is disregarded as a nullabilty operator when in trough it inverts the result of the check. Thus to avoid confusion there should be an optional rule to disallow use of that operator.

## Kind

Guard against confusion while reading code. Thus it guards more or less against errors.

## Good Examples 

`!(exception is MyException)`

## Bad Examples

`exception is! MyException`

## Discussion

If this is accepted I will move forward and propose add `!is` to be added to the dart language so developers decide if they prefer to literally read "is not" (which was a great idea before nullability was a thing) or to have consistency in the way that prefixed `!` are always about falsyness and suffixed `!` are always about null, which IMHO would now be the approach of least surprises.

I am going the route of proposing to add a linter rule first as this is a less invasive change that merely adds the option of choosing your own preference. This way over time it should be possible to determine the common preference by scanning open source git repos for their setting.

For now this would be the inverse of `prefer_is_not_operator`. If `!is` gets introduced this rule should be deprecated in favour of a `prefer_not_is_operator`.

### Discussion checklist

- [x] List any existing rules this proposal modifies, complements, overlaps or conflicts with.
- [x] List any relevant issues (reported here, the [SDK Tracker], or elsewhere).
- [x] If there's any prior art (e.g., in other linters), please add references here.
- [ ] If this proposal corresponds to [Effective Dart] or [Flutter Style Guide] advice, please call it out. (If there isn’t any corresponding advice, should there be?)
- [x] If this proposal is motivated by real-world examples, please provide as many details as you can.  Demonstrating potential impact is _especially valuable_.

[Writing Lints]: https://github.com/dart-lang/linter/blob/main/doc/writing-lints.md
[Effective Dart]: https://dart.dev/guides/language/effective-dart
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[SDK Tracker]: https://github.com/dart-lang/sdk/issues

**Comment by srawlins** [comment]
While this is a great tactic for easing the path to a breaking change (we've got several other lint rules in the pipeline for the same purpose), we should only implement this if the language team intends to change the `is!` operator to `!is`. CC @munificent who was in the thread at https://github.com/dart-lang/language/issues/2425.

Otherwise we can only accept lint rules into the core linter which are expected to be recommended in some fashion by the Dart or Flutter teams.

**Comment by DaDummy** [comment]
Oh my. Thanks for pointing that out! The issue search function sadly does not really work well with `!is` or `is!` :(

As `!is` currently does compile and produces a different albeit mostly unintended behaviour, a language change might really make sense no matter how far it would actually progress as it would at least help people avoid the currently existing pitfall.

If this has any chance of success I am willing to write up the proposal for the language change and a migration path.

Short abstract of what migration path I would propose:

1. Optional: Add a recommended linter warning with a fixup that replaces `foo !is Type` by `foo! is Type` (will only affect unformatted code anyway)
2. Start recognizing `!is` as its own entity but just throw a compiler error when it is encountered, to make sure any affected code breaks instead of silently changing its behaviour.
3. With the following major update have `!is` and `is!` do the same and remove the linter warning from 1.
4. Optional: Update/add linter rules so they prefer `!is` over `is!` and gently migrate code over.
5. Optional: Later on maybe deprecate and remove `is!`

**Comment by munificent** [comment]
I don't think there's any desire on the language team to actually remove `is!` from the language in favor of `!is`. There is *definitely* no appetite for removing it and having users write `!(o is T)`. The shorthand `is!` operator was added specifically because `(o is T)` is so disliked.

The `is!` operator is very very widely used and there have been almost no complaints from users, even after null safety shipped.

However, code like `foo !is Bar` is very likely to be a user error because while it's valid Dart, the spacing indicates that the user thinks they are calling a Kotlin-like `!is` operator instead of the postfix `!` followed by `is` that they're actually doing. What I'd suggest is a lint that fires if it sees an `is` operator where the lefthand side is a `!` and where there is no space between the `!` and `is`.

**Comment by srawlins** [comment]
My [first comment](https://github.com/dart-lang/linter/issues/3611#issuecomment-1224085134) makes no sense to me now; maybe the summary was changed after i wrote it. In any case, as the summary is now, I don't think we can recommend `!(o is T)` because that does not have type promotion like `o is! T` does.

**Comment by bwilkerson** [comment]
I agree, so I'm going to close this issue.
