### ISSUE TITLE
consider extending `avoid_positional_boolean_parameters` to include record literals

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3627]
Docs: https://dart-lang.github.io/linter/lints/avoid_positional_boolean_parameters.html.

**Comment by bwilkerson** [comment]
I haven't formed an opinion yet, but I wonder whether or not we want to treat record literals like argument lists and/or record types like parameter lists. The syntax is intentionally largely the same, so maybe, but we call these 'fields' rather than 'parameters' or 'arguments', so on some level we're thinking of them as being distinct kinds of things.

That said, I could certainly see a lint that would flag this case. I could also see a lint that would flag when there are two positional fields with the same type (a superset of `avoid_positional_boolean_parameters`).

**Comment by munificent** [comment]
It's *probably* not a good idea to have positional record fields, but I don't know if I want to eagerly ship a lint (or extend an existing lint) to steer people away from it yet. It might be worth being silent to see if valid unanticipated use cases appear.

**Comment by pq** [comment]
I'm all for waiting on this one.

Thanks!
