### ISSUE TITLE
ensure `exhaustive_cases` works with switch-expressions

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3675]
https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#switch-expression

**Comment by srawlins** [comment]
I think the only case where a non-exhaustive switch expression is allowed by the language is one where pre-null safe types flow into the switch expression. [See here](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#switch-expression-1). Otherwise they must be [exhaustive](https://github.com/dart-lang/language/blob/master/working/0546-patterns/exhaustiveness.md).

I think it would be low priority to support `exhaustive_cases` in a switch expression just for pre-null safe code. I don't actually think we can write the lint to report something that wouldn't already be reported as illegal.

**Comment by pq** [comment]
Oh!  That's fantastic.  I didn't realize the exhaustiveness promise was so inclusive.

> I think it would be low priority to support exhaustive_cases in a switch expression just for pre-null safe code. I don't actually think we can write the lint to report something that wouldn't already be reported as illegal.

💯 

I'll close this out then.  Thanks!
