### ISSUE TITLE
Mention in the docs for unnecessary_breaks that it's a Dart 3.0 feature

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/linter#4131]
The [docs for unnecessary_breaks](https://dart.dev/tools/linter-rules#unnecessary_breaks) should mention that they are enforcing a Dart 3.0 feature. The lint has no effect on code with sdk constraints lower than 3.0.0.

**Comment by parlough** [comment]
I wonder if it would make sense for rules in general to specify a required language version, at least for documentation purposes, to avoid confusion on why a lint isn't applying. 

Another recent example I can think of is [`unnecessary_library_names`](https://github.com/dart-lang/linter/issues/3882) which would require a language version of 2.19.

**Comment by pq** [comment]
100%.

We did something kind of _ad_hoc_ w/ `invalid_case_patterns` but I'd love something more general.

I'd sort of imagined we could have the doc generator look at `since` info in the new `State` objects attached to lints but haven't finished the thought. 😬 

In the meantime, yes, let's **at least** fix these up for Dart 3.0.
