### ISSUE TITLE
Add notes about analyzer API usage to the contributing docs.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#416]
Things to add:
* [x] PR code review process (https://github.com/dart-lang/linter/pull/418)
* [ ] note about analyzer API access

**Comment by alexeieleusis** [comment]
Something that I would like to have is merge commits to have an easy way to find the PR and the discussion it contains. I really prefer linear history in the repo, but is way more valuable IMO the discussion.

**Comment by pq** [comment]
@alexeieleusis 

> Something that I would like to have is merge commits 

Could you elaborate with an example?  (Not sure I'm following -- and go easy on me, I'm am avowed git neophyte! 😊 )

**Comment by alexeieleusis** [comment]
If you look here https://github.com/dart-lang/linter/commits/master in the commits on 2/8/2017 there is
https://github.com/dart-lang/linter/commit/ca887cfca059435c6ba175d5b81c6a461ce40cc7 (which I merged) and I can't find an easy way to navigate to the pull request, in this case the change itself is so simple that is not needed, but for instance https://github.com/dart-lang/linter/commit/a9c1a88e2f573e88b2713001060428721465d2ab which took 4 months to land the very next commit points to https://github.com/dart-lang/linter/pull/229

Probably is a matter of configuring github correctly or something like that, because I expected that by clicking the merge button the commit would be created automatically.

**Comment by pq** [comment]
Thanks @alexeieleusis!  I'll do some poking around.  In the meantime, if you have any tips for how we might better configure, I'm all ears!
