### ISSUE TITLE
Enforce `future` and/or `initialData` for `FutureBuilder`

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/linter#4309]
See https://github.com/flutter/flutter/issues/83081 for justification and the like.

I'm happy to take on initial implementation duties.

**Comment by srawlins** [comment]
Could be accomplished with something like https://github.com/dart-lang/sdk/issues/47712, like a `@OneOf(['future', 'initialData'])` annotation on FutureBuilder.

**Comment by pq** [comment]
Great question, Sam!

**Comment by caseycrogers** [comment]
> Could be accomplished with something like [dart-lang/sdk#47712](https://github.com/dart-lang/sdk/issues/47712), like a `@OneOf(['future', 'initialData'])` annotation on FutureBuilder.

IMO this isn't quite the ideal solution.

If a dev is not providing any value for `future` (null or otherwise), then why are they using a future builder in the first place? In this case it's known at compile time that the future builder will always build with `ConnectionState.nothing` and `initialData` and the future builder isn't doing anything.

I would guess that not providing a `future` is either a weird antipattern or a mistake in ~100% of cases. **Therefor, we should provide a lint warning whenever `future` is omitted, whether or not `initialData` is provided/non-null.** If there are rare cases where it's desirable to provide a future builder without a `future`, then devs can either hush the lint warning or write `future: null`.

**Comment by srawlins** [comment]
> I would guess that not providing a future is either a weird antipattern or a mistake in ~100% of cases. Therefor, we should provide a lint warning whenever `future` is omitted, whether or not `initialData` is provided/non-null. If there are rare cases where it's desirable to provide a future builder without a `future`, then devs can either hush the lint warning or write `future: null`.

We need guidance from Flutter here on whether it is reasonable to omit `future`. CC @goderbauer . If it is, I don't think we should have a lint rule banning its omission. If it isn't, Flutter could make it required, or split into two constructors or something.

**Comment by caseycrogers** [comment]
Yeah, this issue is a spin off from a request to make `future` required. My feeling is the best path here is:
1. Add a lint warning for omitting `future` in `FutureBuilder` and one for omitting `stream` in `StreamBuilder`
2. After devs have had some time to acclimate to the above (~1-2 months in stable?), make `future` and `stream` required arguments

All this is assuming that there are few to no coherent reasons to omit these arguments-my best guess is that the only reason they weren't already required is because the widgets were made before `required` was added as a keyword to Dart and no one got around to updating it. 
I'm looking forward to feedback from the flutter team on this!

**Comment by srawlins** [comment]
There is another request to have the old-school `@required` mean "will be required soon" which we could use. I think that's a good general purpose API for communicating such a change to users.

**Comment by caseycrogers** [comment]
Sounds reasonable. Though I'm worried about bogging this relatively simple change down too much in side projects...for example I wonder if even having a linter in the first place is worth our time or if it'd be better to go straight to having the `required` keyword? The current API is a giant foot gun as it's so easy to forget these arguments and the failure state (UI hanging in dev-defined "data not yet received" state) isn't super obvious. So fixing this seems pretty high ROI and I'd argue for a bias towards getting this done over optimizing the rollout.

If omitting these arguments really is incoherent, then it should be very rare that they are omitted in live code in which case this should be a very low impact breaking change. Is there a good way to gut check what percentage of Flutter projects would be impacted by a breaking change?

**Comment by domesticmouse** [comment]
This is no longer required - replaced by https://github.com/flutter/flutter/pull/125838
