### ISSUE TITLE
Add Lint to dissuade users from creating multiple goldens in a single test

### ISSUE THREAD

**Issue by pdblasi-google** [dart-lang/linter#4613]
Golden tests can be pretty flaky in and of themselves, and the flow is made worse when users have multiple goldens in a single test. If a user does that, it means that you'd have to make multiple passes through the test to update each golden. It'd be great to have a lint that drives a user to use `AnimationSheetBuilder` when multiple golden checks are defined in a single test.

**Comment by srawlins** [comment]
Can you explain what goldens you are referring to? Or what a golden check is? Or how `AnimationSheetBuilder` would disable a diagnostic from being reported?

In order to implement a linter rule, we'd need very specific notions of what code should trigger a diagnostic. Any details would be appreciated. Thanks!
