### ISSUE TITLE
[Wildcard Variables] support for `unnecessary_final`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#5043]
It seems like we should report `unnecessary_final` on all wildcard variables as wildcards are not assignable.

Thoughts?

/cc @kallentu @bwilkerson @lrhn

**Comment by lrhn** [comment]
As I read the `unnecessary_final` lint, it should apply to all local variable declarations marked `final`, so there is no reason it shouldn't apply to a wildcard variable declaration. (Unless it's considered "not a variable declaration" entirely, what it shouldn't for this purpose.)

Wildcard (non-parameter) variables are never necessary. Any warning on top of that is not the most important warning, and shouldn't be necessary.

If you have them anyway, I'd say that `final` is _correct_ since the variable cannot be read.
If you are the kind who used `final` at all, ... then I guess you won't have the `unnecessary_final` lint.

So agree, no exception should be made for wildcard variables.

**Comment by pq** [comment]
Thanks Lasse!

This is WAI and tested via https://github.com/dart-lang/sdk/commit/f4a5b2d9577389b2928c42eb6bfa1a369576b117.
