### ISSUE TITLE
invalid_runtime_check_with_js_interop_types is slow

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#5106]
I just ran the benchmark script over the linter codebase and it shows the following table (snipped):

|Timings|                                                       ms|
|---|-------------------------------------------------------------|
invalid_runtime_check_with_js_interop_types        |          117
document_ignores                                      |        70
deprecated_member_use_from_same_package         |              47
unreachable_from_main                              |           46
always_specify_types                                |          42
avoid_redundant_argument_values           |                    40
prefer_double_quotes                                |          36
analyzer_use_new_elements                      |               33
use_named_constants                                 |          33
unintended_html_in_doc_comment            |                    32
avoid_positional_boolean_parameters          |                 29
eol_at_end_of_file                                     |       29
lines_longer_than_80_chars                     |               29
directives_ordering                                  |         28
use_late_for_private_fields_and_variables        |             26
non_constant_identifier_names                      |           26
unnecessary_overrides                                    |     26
avoid_web_libraries_in_flutter [flutter]            |          24
require_trailing_commas                         |              23
no_wildcard_variable_uses                     |                22

These are all of the rules that cumulatively took more than 20ms.

**Comment by pq** [comment]
Interesting. Thanks for running this!

The lack of regular benchmarking is something I really miss from the old GH workflow.

`document_ignores` is unfortunate too. It'd be interest to think about how we could optimize this now that the linter and analyzer are in the same repo. (Note that analyzer inspects ignores too so this work is being duplicated.)

**Comment by bwilkerson** [comment]
Unless I missed something, I looks like the worst offenders aren't in any of the core, recommended, or flutter lint sets, so that's good.

I have to wonder, though, why `prefer_single_quotes` isn't on the list when `prefer_double_quotes` is. I would have expected them to have nearly identical timings.

**Comment by pq** [comment]
When we were benchmarking regularly I made a concerted effort to get the core/recommended lints sped up. We've been pretty conservative in adding new ones since then so maybe we've just been lucky...

As for `prefer_double_quotes`, I wonder if this is because when analyzing source with single quotes it can't bail out early. I'd be curious to see if the results flip on a codebase that preferred double quotes.

**Comment by srujzs** [comment]
:( I suspect that the cost of `invalid_runtime_check_with_js_interop_types` is probably due to the [`canBeSubtypeOf`](https://github.com/dart-lang/sdk/blob/74804fd092799ba9388cdd7ec4f6f6148b82dd07/pkg/linter/lib/src/rules/invalid_runtime_check_with_js_interop_types.dart#L338) check that occurs for every single `is` and `as` expression. We do an extension type erasure for each type as well, but that should be a trivial no-op if no interop type is included, so I'm guessing it's really the `canBeSubtypeOf`.

Maybe it might be faster to use a type visitor to check whether the two types contain a JS interop type somewhere first? `canBeSubtypeOf` does a load of other checks, so this may be faster. Are there instructions to run the benchmarking?

> Unless I missed something, I looks like the worst offenders aren't in any of the core, recommended, or flutter lint sets, so that's good.

`invalid_runtime_check_with_js_interop_types` is now in the recommended set alas.

**Comment by srawlins** [comment]
> Are there instructions to run the benchmarking?

A search of the README and the `doc/` directory tells me, "no". ☹️  I was looking at this script recently which is the only reason I ran it. If you're sitting in the `pkg/linter` directory, you can run

```none
dart tool/cli.dart --config ./analysis_options.yaml --benchmark .
```

I don't think the CWD matters, but I think it's important to pass a config file and end with the director(y|ies) you wish to analyze.

This will soon move to something like `tool/benchmark.dart`, when https://dart-review.googlesource.com/c/sdk/+/388946 lands.

**Comment by srawlins** [comment]
I tried using DevTools but that did not reveal much to me. I then just commented out a few pieces based on your hypothesis, @srujzs and saw:

| feature set | ms |
|---|---|
| base | 136 |
| w/o canBeSubtypeOf | 5 |
| w/ canBeSubtypeOf but w/o eraseTypes | 107 |

So yes it looks like just the basic `canBeSubtypeOf` is very expensive!

> Maybe it might be faster to use a type visitor to check whether the two types contain a JS interop type somewhere first?

I like this idea. Would the `TypeVisitor` just track whether any nested type `_isDartJsInteropType`? Or `_isUserJsInteropType`? Or the WASM one? 😅  I'd be happy to look into this.

**Comment by srujzs** [comment]
Thanks for the instructions and looking into the performance of `canBeSubtypeOf`!

> I like this idea. Would the TypeVisitor just track whether any nested type _isDartJsInteropType? Or _isUserJsInteropType? Or the WASM one? 😅 I'd be happy to look into this.

Kind of - I believe the goal would be to check if either `_isDartJsInteropType` or `_isUserJsInteropType` is true, but they likely repeat some work that we can instead move to a separate helper. I can take this on, it gives me a chance to verify the above instructions work. :)

**Comment by srawlins** [comment]
Excellent, thanks @srujzs !

**Comment by srujzs** [comment]
Benchmarking the linter directory with [this CL](https://dart-review.googlesource.com/c/sdk/+/389761) (with `dart tool/benchmark.dart --config ./analysis_options.yaml .`), which avoids checking types if they don't contain any interop types, results in 5ms.

Granted, that's mostly because the linter directory is using no JS interop, but the ratio of JS interop-related checks/casts to other checks/casts will be low anyways.

**Comment by srawlins** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/9fae030ae9f51e045493f2c8d2896060c4a74a10
