### ISSUE TITLE
common developer bad  coding style issue of nullable list iteration using for-loop

### ISSUE THREAD

**Issue by raymondmakz** [dart-lang/linter#5125]
Hi everyone, 
I am have encounter a problem about a common coding style which potential trigger runtime exception.
But I cannot really tell it is related to dart-core or linter issue.

My dart version is 3.5.1
I have read the 3.7.x lint rule and test case file for omit_obvious_local_variable_types and specify_nonobvious_local_variable_types.
Ref: https://github.com/dart-lang/linter/issues/3480

Here is the code:
```
class Fruit
{
  final String name;
  const Fruit(String name) : this.name = name;
  
  @override
  String toString(){
    return '(Fruit name: $name)';
  }
}

List<Fruit> getFruitList(){
  return <Fruit>[Fruit('pear'), Fruit('apple')];
}

List<Fruit>? getNullableFruitList(){
  return <Fruit>[Fruit('pear'), Fruit('apple')];
}

Map<String, Fruit>? getNullableFruitMap(){
  var map = <String, Fruit>{
    'PEAR': Fruit('pear'), 
    'APPLE': Fruit('apple'),
  };
  return  map;
}

void main(){

  var fruitList = getFruitList();
  var nullableFruitList = getNullableFruitList();
  var nullableFruitMap = getNullableFruitMap();

  //Case 1
  for (var fruit in fruitList ?? []){      //$fruit inferenced as dynamic, even fruitList is not null
    print(fruit.name);
    print(fruit.non_exist_prop);     //NO LINT, But Unhandled exception: NoSuchMethodError: Class 'Fruit' has no instance getter 'non_exist_prop'.
  }

  //Case 2
  for (var fruit in nullableFruitList ?? <Fruit>[]){   //use implict typed list, $fruit inferenced as Fruit
    print(fruit.name);
    print(fruit.non_exist_prop);     //LINT, undefined_getter
  }

  //Case 3
  for (var fruit in nullableFruitList ?? []){      //$fruit is inferenced as dynamic
    print(fruit.name);
    print(fruit.non_exist_prop);   //NO LINT, But Unhandled exception: NoSuchMethodError: Class 'Fruit' has no instance getter 'non_exist_prop'.
  }

  //Case 4
  for (var fruit in nullableFruitList ?? []){      //$fruit is still inferenced as dynamic
    print((fruit as Fruit).name);
  }

  //Case 5
  for (Fruit fruit in nullableFruitList ?? []){
    print(fruit.name);
    print(fruit.non_exist_prop);   //LINT, undefined_getter
  }

  //Case 6
  var nonNullableFruitList = nullableFruitList ?? [];   //$nonNullableFruitList is inferenced as List<Fruit>
  for (var fruit in nonNullableFruitList){      //$fruit is inferenced as dynamic
    print(fruit.name);
    print(fruit.non_exist_prop);   //LINT, undefined_getter
  }

  //Case 7
  (nullableFruitList ?? []).forEach((f) {
    print(f.name);
    print(f.non_exist_prop);   //LINT, undefined_getter
  });

  for (var mapEn in nullableFruitMap?.entries ?? {}){}   //$mapEn is inferenced as Object? , because {} is Set<dynamic> 
  for (var mapEn in nullableFruitMap?.entries ?? []){}   //$mapEn is inferenced as Object? , because {} is List<dynamic>
  for (var mapEn in (nullableFruitMap ?? <String, Fruit>{}).entries){}   //$mapEn is inferenced as MapEntry<String, Fruit>

}
```

Look at case 1, case 3 and case 6.
It seems that the for-loop declaration have its own type inference on null-coalesce logic.

**Comment by eernstg** [comment]
You need to consider the context type of various expressions. In particular, the context type for the iterable of a for-in statement is obtained from the declaration of the iteration variable (or from the existing iteration variable, if it is a for-in statement that doesn't declare this variable, as in `for (existingVariable in myList) ...`).

You can explore this context type using examples like these ones:

```dart
X whatever<X>() {
  print('X is $X');
  return <Never>[] as X;
}

void main() {
  for (int _ in whatever()) {} // 'X is Iterable<int>'.
  for (String _ in whatever()) {} // 'X is Iterable<String>'.
  for (var _ in whatever()) {} // 'X is Iterable<Object?>'.
}
```

This illustrates that if the type of the iteration variable is `T` then the context type for the iterable is `Iterable<T>`. With `var` there is no context type (it's the "unknown type" `_`), which means that `whatever()` is inferred as `whatever<Iterable<dynamic>>()`.

In 'Case 1', `fruit` is then inferred to have type `dynamic`, which means that you get a dynamic check rather than a compile-time error when you try to call `non_exist_prop`.

In 'Case 2', you're providing the type argument in `<Fruit>[]` which means that the type of the iterable as a whole is `List<Fruit>`.

'Case 3' is like case 1 (the left-hand operand of `??` is now nullable, but this makes no different for the typing of the `??` expression as a whole).

And so on.

The point is that the `??` expression gets a type which is determined in several steps, and some of them will yield an `Iterable<dynamic>` or `List<dynamic>`, and this will cause the iteration variable to get an inferred type (when it doesn't have a type annotation of its own) of `dynamic`, and then you won't get any errors for calling `non_exist_prop`. Conversely, when the type of the iteration variable isn't `dynamic`, you get static typing.

It is somewhat confusing because inference of `??` is somewhat complicated, but it is all working as intended.

**Comment by eernstg** [comment]
The lints shouldn't play a big role here: They're concerned with having or omitting type annotations on local variable declarations, and the interesting question for this code is which type the variable gets when there is no type annotation (so it's not relevant to add a type annotation, or remove it).

The lines marked `//LINT` are actually not locations where a lint message is emitted, they are locations where a compile-time error is encountered, which is true for all the cases where `non_exist_prop` is invoked, but the iteration variable doesn't have type `dynamic`.

**Comment by eernstg** [comment]
By the way, you might want to use something like this in your `analysis_options.yaml`:

```yaml
analyzer:
  language:
    strict-raw-types: true
    strict-inference: true
    strict-casts: true

linter:
  rules:
    - avoid_dynamic_calls
```

**Comment by raymondmakz** [comment]
Thanks @eernstg for answering my question.
I gains more insight on the `??` type inference now.
Understand lint rules `specify_nonobvious_local_variable_types` not main concern this issue.
`var xx = someLIst ?? []` is acting differently on function body and inside for-loop declaration trouble me most. 

Wait to see any changes in dart 3.6/3.7 release, since i just come across this seem dart core team already had a glance on this matter: 
https://github.com/dart-lang/sdk/issues/55436


Sadly, `strict-raw-types`, `strict-inference` , `strict-casts` and even `avoid_dynamic_calls` can make teammates who work on the project unhappy.
