### ISSUE TITLE
Implement DON’T discard errors from catches without on clauses.

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#524]
From [Effective Dart](https://www.dartlang.org/guides/language/effective-dart/usage#dont-discard-errors-from-catches-without-on-clauses)

**Comment by JPaulsen** [comment]
@bwilkerson @pq is this necessary to implement? Because if you have something like this.

```dart
try {
}
catch(e) {
  // ignore
}
```

The analyzer will say you, "The exception variable 'e' is not used, so the 'catch' clause can be removed."

**Comment by zoechi** [comment]
I don't get a hint for the unused variable 'e' with above code. 

I also don't get any hint for

```dart
try {
}
catch(_) {}
```

**Comment by bwilkerson** [comment]
There is no hint when the exception parameter is not used and there is no `on` clause because at that point the exception parameter is required and there isn't any reasonable way the user could get rid of the hint.

> is this necessary to implement?

How would you catch this case? Any exception parameter that is not referenced within the `catch` clause? It will be marked as dead code if there is an `on` clause, and I don't think it's useful to create a lint that cannot be removed. I don't think we need a lint for this.

**Comment by JPaulsen** [comment]
You were right, without on clauses it does not hint that.

And yes, if it has the on clause it will be mark as dead code, and without the on will be linted as avoid lints without on, so I will close this issue.
