### ISSUE TITLE
Implement DON’T use async when it has no useful effect.

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#583]
From [Effective Dart](https://www.dartlang.org/guides/language/effective-dart/usage#dont-use-async-when-it-has-no-useful-effect)

**Comment by JPaulsen** [comment]
```
You are using await. (This is the obvious one.)

You are returning an error asynchronously. async and then throw is shorter than return new Future.error(...).

You are returning a value and you want it implicitly wrapped in a future. async is shorter than new Future.value(...).

You don’t want any of the code to execute until after the event loop has taken a turn.
```

@bwilkerson About the 4 cases in Effective Dart we can only automate the first two, should we proceed to implement that?

**Comment by bwilkerson** [comment]
I'm not entirely sure what you'd be checking for in order to determine that `async` has no useful effect. I guess you're assuming that the list from the guide is a complete description of what makes async useful, and would check for the absence of any condition that would make it useful.

For the first, I guess you'd check to see if the method does not use `await`, which is easy to do.

For the second, would you check for any use of `throw` or `rethrow`? (Technically you'd also want to look for the invocation of any function that could throw, but we don't have that information.)

For the third, would you check for any use of `return`?

(There's obviously no way to check the fourth.)

It seems unlikely that there would be very many methods that are marked with `async` that neither throw nor return nor use `await`, so I don't know how much value this would add.

**Comment by JPaulsen** [comment]
Ok, so do we pass this rule and close the issue?

**Comment by bwilkerson** [comment]
I think there are several possible next steps, but the choice is yours (with help from @alexeieleusis). The ones I can think of are:
1. Decide that this rule isn't worth implementing.
2. Decide that this rule isn't worth implementing right now but might be worthwhile later.
3. Figure out a way to measure the usefulness of `async` that is better than what I described above.
4. Prove that my intuition is wrong. [0]
5. Ignore me and proceed. (After all, if I'm right you won't produce any lints, which *does* mean that there won't be any false positives :-)

I think your course of action should be determined by how much value you think this rule will bring to users.

[0] After all, I'm only guessing about how many cases you'd be able to catch. You could take some measurements to see whether I'm right or wrong. For example, run over several bodies of code and count (a) the number of functions (top-level, methods, local), (b) the number of functions that are marked with `async`, and the number of those that do not contain either a `throw` or `return`.
