### ISSUE TITLE
Review `0.1.31` changes.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#648]
I fat-fingered and pushed a commit (https://github.com/dart-lang/linter/commit/609ff7686c9d942b69922e36a4373fe5b2ef7643) that was meant to be a PR.

Please take a quick look.  Happy to revert if needed.

Note there is some rule name normalization.

@bwilkerson 

FYI @a14n @alexeieleusis

**Comment by pq** [comment]
FYI @zoechi

**Comment by pq** [comment]
@bwilkerson: here's the diff

https://github.com/dart-lang/linter/commit/609ff7686c9d942b69922e36a4373fe5b2ef7643

**Comment by bwilkerson** [comment]
A couple of minor comments, but otherwise lgtm.

lib/src/rules.dart

You changed `do_not_create_setter_without_getter` to `avoid_setters_without_getters`. Should we similarly rename `do_not_catch_errors` and `do_not_check_for_null_in_equality_operators`?

We generally try to keep the list of registrations in alphabetic order.

lib/src/rules/avoid_returning_null.dart

Personally, I think we should remove all `library` directives, but it's your call.

**Comment by pq** [comment]
Thanks!

> You changed do_not_create_setter_without_getter to avoid_setters_without_getters. Should we similarly rename do_not_catch_errors and do_not_check_for_null_in_equality_operators?

> We generally try to keep the list of registrations in alphabetic order.

PR on the way.

> Personally, I think we should remove all library directives, but it's your call.

Agreed.  I made a note to myself to remove them all (and turn on that lint) after this lands. 👍
