### ISSUE TITLE
New lint: keep names of positional arguments in overridden functions consistent with super

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/linter#904]
See https://github.com/dart-lang/sdk/blob/fed7120b070160ee6a4c2fe95fb442feadf2c96b/sdk/lib/collection/maps.dart#L141

Argument named `entries`. No doc comment. So the comments are inherited from

https://github.com/dart-lang/sdk/blob/ec7029daf6146514a9ca0567621fc3665f85f7ff/sdk/lib/core/map.dart#L257

Argument named `newEntries` – so when Dartdoc generates docs for this, the parameter reference fails.

CC @jcollins-g

**Comment by kevmoo** [comment]
See https://dart-review.googlesource.com/c/sdk/+/43201

**Comment by jcollins-g** [comment]
+1.  I've considered adding some duct-tape in dartdoc so it understands this, but the code will be nicer to read if it is kept consistent.

**Comment by a14n** [comment]
Should the lint apply only for methods without doc comment ?

**Comment by kevmoo** [comment]
> Should the lint apply only for methods without doc comment ?

For the core issue I'm hitting, yes.

I think there is an argument for doing it everywhere, but it's a much weaker argument. 😄

**Comment by jcollins-g** [comment]
To cover the dartdoc problem completely, the actual requirement is:

- For any method/operator/setter that is documented by Dartdoc but has no doc comment associated with it, its parameter name should match that of the superclass where the doc comment is inherited from.

There's an argument for having this lint inside dartdoc because it actually knows all these things and won't bother alerting when it doesn't matter. The linter will have to approximate but that's a tradeoff that's reasonable because more people will see it if the linter says it -- and having this consistent everywhere could make code easier to read in general.

**Comment by kevmoo** [comment]
The lint kinda already exists in dartdoc – it could be more specific about
the problem, though.

My --log-as-json [sik] was designed to start enabling dartdoc to have a
test/CI mode to catch these...
