### ISSUE TITLE
Unexpected hash_and_equals lint when hashCode is overridden but == is not

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/linter#976]
Based on [the description of the lint and its rationale](http://dart-lang.github.io/linter/lints/hash_and_equals.html ), 
> DO override hashCode if overriding ==.

I would expect overrides to `hashCode` without overrides to `==` to not trigger this lint, but they do:
```dart
class Foo {
  int get hashCode => 1;
}
```
>info: Always override `hashCode` if overriding `==` (hash_and_equals at [foo] lib/foo.dart:3)

It would be nice if the behavior of the lint was fully captured in its documentation (whether that means adjusting the behavior or adjusting the documentation). The lint message is also a little confusing as-is, since `==` is not being overridden.

**Comment by matanlurey** [comment]
I could be wrong, but I think its probably valid _code_ to override `hashCode` without `equals`. It's totally valid for every object to have a `hashCode = 1` (as in your example), it just means that you will _always_ collide in a `Map` / `Set` - but your implementation isn't _wrong_.

(That being said, overriding `hashCode` (or `==`) in classes that are mutable doesn't make a lot of sense anyway, because it means the hash code and/or equality can change even though the object is already added to a map/set - so maybe that is another potential lint opportunity)

**Comment by kevmoo** [comment]
thoughts @pq ?

**Comment by pq** [comment]
I agree w/ @matanlurey.  I think this is not invalid exactly but I think generally not a good idea (and certainly likely to cause head-scratching for anyone looking at your class implementation).

@kevmoo: do you have a concrete use case where it's desirable?

**Comment by kevmoo** [comment]
> do you have a concrete use case where it's desirable?

I do not. I think this is the type of thing where the 99% case wins out – although I understand you're thinking @greglittlefield-wf

**Comment by pq** [comment]
> The lint message is also a little confusing as-is, since == is not being overridden.

My thinking is we should probably leave the semantics as is but go ahead and update the docs and message.

fyi @bwilkerson

**Comment by pq** [comment]
Thanks again for the report @greglittlefield-wf.  This is a great case study in where better docs and more specific error messages can make a big difference.  I've got a PR out that makes things a little better but please do chime in if you have ideas for refinements.

Cheers!

**Comment by pq** [comment]
Thanks for the kind words!  Needless to say, the product would really suffer if not for thoughtful feedback like yours so please, keep it coming! 💎
